### ISSUE TITLE
[1.17] Breaking sound with shift+hammer

### ISSUE THREAD

**Issue by kaiserkalt** [kwpugh/gobber_fabric-1.17#2]
There is no breaking sound when you hold shift and break blocks with a hammer. I haven't tested this with the excavator

**Comment by kwpugh** [comment]
Why are you holding shift to break?

I will take a look.

**Comment by rc8marcelo** [comment]
I can confirm that hammers work with sounds on my end even if you press shift. 

> Why are you holding shift to break?

Not sure about OP but I do that with my hammer at times because it has Fortune 3 on it. Before I got my other Fortune PickAxe, that was my go-to for getting ores. On a separate note, I don't know if its a bug or intentional but fortune on a hammer only works on the actual block being broken. Other ores surrounding the area a hammer breaks for me doesn't yield fortune effects.

**Comment by kwpugh** [comment]
closing, no further work here.
