### ISSUE TITLE
[1.18.1] Staff Of The Farmer lag

### ISSUE THREAD

**Issue by Swiftess** [kwpugh/gobber_fabric-1.17#37]
If you are holding the staff of the farmer it causes extreme lag
![2021-12-10_15 56 47](https://user-images.githubusercontent.com/95922721/145585504-bc4bea5c-a6a1-4af7-a306-4180a63cb6d2.png)
![2021-12-10_15 57 12](https://user-images.githubusercontent.com/95922721/145585506-d93ccf47-4bd3-4dfd-9d0e-14bb3747ca8b.png)
.

**Comment by kwpugh** [comment]
yes that can happen since it is search for blocks to grow.  I have done quite a bit tweaking to reduce that, but it is part of the deal when you search for blocks.  You might try reducing the range in the config.  If that doesn't help, simply disable it.

Having an I5 2.5Ghz and 2GB for minecraft doesn't help either.

**Comment by kwpugh** [comment]
this is consistent with what the item is designed to do, no more work in the short term to do.
