### ISSUE TITLE
[1.19] Bow does not play proper Zooming effect while holding button 

### ISSUE THREAD

**Issue by ardissaps** [kwpugh/gobber_fabric-1.17#73]
Vanilla does zooming when hold right click

**Comment by kwpugh** [comment]
This is an issue across all the bows in my mods.

**Comment by kwpugh** [comment]
yeah, I'm researching it.

**Comment by kwpugh** [comment]
ok, I figured it out.

It will be going into Emerald Tools first since that was reported first.

The zoom will be about 2.5x the vanilla zoom, but it can be adjusted in the config.

I will do Gobber next, then MoreGems after that.

Vanilla Zoom
![2022-06-20_12 39 24](https://user-images.githubusercontent.com/8809210/174659020-f116f838-e10d-4331-9e30-03c4f2ec1046.png)

My Zoom, at medium setting
![2022-06-20_12 39 39](https://user-images.githubusercontent.com/8809210/174659079-b5e9faa1-f816-4029-8dbe-d2c866c6069a.png)

**Comment by kwpugh** [comment]
Just uploaded new version .17 to curse forge with new zoom

**Comment by ardissaps** [comment]
> Just uploaded new version .17 to curse forge with new zoom
> 

Thank you very much! Waiting for .18.2 too, but not in hurry! :)

**Comment by kwpugh** [comment]
I won't be backporting to 1.18.2.   1.19 gets new features, 1.18.2 just bug fixes.  Sorry.

**Comment by kwpugh** [comment]
MoreGems  1.19 complete.  Closing.

**Comment by ardissaps** [comment]
> I won't be backporting to 1.18.2. 1.19 gets new features, 1.18.2 just bug fixes. Sorry.

Does bow zoom inclued in bug fix or new feature?

**Comment by ardissaps** [comment]
> Bows worked fine, zoom is a feature.

ok so I guess I will install again when my modpack ready for 1.19, still misssing many my important mods list

**Comment by kwpugh** [comment]
I added the bow feature to the v75 for 1.18.2 I just pushed to curse forge.  enjoy.

**Comment by ardissaps** [comment]
> I added the bow feature to the v75 for 1.18.2 I just pushed to curse forge. enjoy.

Thank you very much! :p
